-- ============================================================
-- Script SQL - API REST de Gestión de Pedidos
-- Base de datos: PostgreSQL
-- ============================================================

-- Paso 1: Crear la base de datos (ejecutar conectado a postgres)
CREATE DATABASE db_pedidos;

-- Paso 2: Conectarse a db_pedidos y ejecutar el resto
-- \c db_pedidos

-- ============================================================
-- TABLAS
-- ============================================================

CREATE TABLE public.clientes (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      character varying(100)  NOT NULL,
    apellido    character varying(100)  NOT NULL,
    dni         character varying(20)   NOT NULL UNIQUE,
    correo      character varying(150)  NOT NULL UNIQUE,
    fecha_registro timestamp(6) WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE public.productos (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      character varying(150)  NOT NULL,
    descripcion character varying(300),
    precio      double precision        NOT NULL,
    stock       integer                 NOT NULL,
    estado      boolean                 NOT NULL
);

CREATE TABLE public.pedidos (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_pedido timestamp(6) WITHOUT TIME ZONE NOT NULL,
    estado       character varying(50)  NOT NULL,
    total        double precision       NOT NULL,
    cliente_id   bigint                 NOT NULL,
    CONSTRAINT fk_pedidos_cliente FOREIGN KEY (cliente_id) REFERENCES public.clientes(id)
);

CREATE TABLE public.detalle_pedidos (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id      bigint           NOT NULL,
    nombre_producto  character varying(150) NOT NULL,
    cantidad         integer          NOT NULL,
    precio_unitario  double precision NOT NULL,
    subtotal         double precision NOT NULL,
    pedido_id        bigint           NOT NULL,
    CONSTRAINT fk_detalle_pedido FOREIGN KEY (pedido_id) REFERENCES public.pedidos(id)
);
